### PR TITLE
Added easy way to overwrite Handler class

### PR DESCRIPTION
**Pull request by TitaniumHocker**
I'm trying to use this library for testing one of my projects, so I have a need to add additional authorization methods locally in my project tests.
For this I need to overwrite the handler class. This PR will make it easy.

### CODE REVIEW

**Comment by swiatek25** [comment]
If you could add a test for sample usage it would be great!

**Comment by TitaniumHocker** [comment]
@swiatek25 Thx, are you planning to release new version in the near future?

**Comment by swiatek25** [comment]
> @swiatek25 Thx, are you planning to release new version in the near future?

Not really sure about that. I have not been doing it before. @carletes could you help out?

**Comment by TitaniumHocker** [comment]
Btw @carletes you can add GitHub CI/CD(GitHub Actions) workflow to automate publishing to PyPI on release tag in repo.
Something like this for example:
https://github.com/TitaniumHocker/gvapi/blob/master/.github/workflows/python-publish.yml

**Comment by carletes** [comment]
@TitaniumHocker: Thanks for your contribution and for the Github Actions tip! I'll implement the push to PyPI during this weekend.

**Comment by TitaniumHocker** [comment]
@carletes Also I have a question. Are you planning to drop old python<3.6 support?

**Comment by carletes** [comment]
Thanks for your PR, @TitaniumHocker! I've added you to the list of this project's collaborators. For any changes you may want to do in the future, just open a PR, ensure tests are green and, if you don't hear from me or from other collaborators in a couple of days, just go ahead and merge it.

@swiatek25: Thanks for looking at this PR, as well!

**Comment by carletes** [comment]
> Are you planning to drop old python<3.6 support?

I still need 2.7, unfortunately :( Hopefully by the end of the year I'll be able to drop 2.7 and 3.5

**Comment by carletes** [comment]
... and 0.9.0 is now on PyPI with your changes, @TitaniumHocker (using GitHub Actions, as you suggested).

**Comment by TitaniumHocker** [comment]
@carletes  Thx. What do you think about migrating to [Poetry](https://python-poetry.org/) as modern packaging and dependency management tool? Also I can add separate linting CI with flake8(+some extensions).

**Comment by carletes** [comment]
> What do you think about migrating to Poetry as modern packaging and dependency management tool?

Go ahead!

> Also I can add separate linting CI with flake8(+some extensions).

Likewise: PR most welcome!

**Pull request merged**
