### PR TITLE
[WIP] Implement list_folder for SFTP server

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Actually I probably need to fill out some more functionality ... marking this as work in progress.

**Comment by carletes** [comment]
Thanks, @mvdbeek! I'm looking now into releasing your recent PRs to PyPI.

**Comment by carletes** [comment]
@mvdbeek: Version 0.3.0 is now on PyPi, including your two pull requests --- thansk a lot!

Have you got a uid in PyPI? I can add you to the list of maintainers of `mock-ssh-server`, so that you may upload new releases if I'm not around.

**Comment by mvdbeek** [comment]
Yes, the username is `mvdbeek`. Thanks a lot!

**Comment by carletes** [comment]
> Yes, the username is mvdbeek

Done! You should now be able to upload new versions of `mock-ssh-server`, @mvdbeek

**Pull request merged**
