### PR TITLE
added remove() to sftp

### PR DESCRIPTION
**Pull request by systemstart**
hi.

i added remove() to the sftp handler.

cheers,

alexander

### CODE REVIEW

**Comment by carletes** [comment]
Thanks, @systemstart --- I also added you as a collaborator to this Github project. I'll cut a new release in PyPI soon.

**Comment by systemstart** [comment]
hi.

do you have a schedule for the new release?

**Comment by carletes** [comment]
Oops, forgot about that, @systemstart --- I just uploaded it to PyPI: https://pypi.python.org/pypi/mock-ssh-server/0.4.0

**Comment by carletes** [comment]
@systemstart: Have you got a uid in PyPI? I can add you to the list of maintainers of `mock-ssh-server`, so that you may upload new releases if I'm not around.

**Pull request merged**
